# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bubble1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bubble1
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'
pod 'Auth0'
pod 'OneSignal', '>= 2.5.2', '< 3.0'
pod 'SendBirdSDK'
end

target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
